### ISSUE TITLE
create .bigsync checksum file from existing backup

### ISSUE THREAD

**Issue by ahmgithubahm** [egorFiNE/bigsync#1]
How about a switch to tell bigsync to write only the .bigsync checksum list file, and not the backup file itself?  This would be useful when introducing the use of bigsync to an existing backup process, without having to make new copies of the source files.

**Comment by egorFiNE** [comment]
Yes, indeed, totally feasible. I will implement this.

**Comment by ahmgithubahm** [comment]
:-)

**Comment by egorFiNE** [comment]
well, yeah.

**Comment by mailinglists35** [comment]
:-))

**Comment by egorFiNE** [comment]
@mailinglists35 @ahmgithubahm talk about long-awaited features, right? Finally done. 0.3.0 pushed.

**Comment by ahmgithubahm** [comment]
yay!
